<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>exe</OutputType>
		<SelfContained>true</SelfContained>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace></RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Discord.Net" Version="3.19.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
	  <None Update=".env">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
      <None Update="rules.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>     
      <None Update="optout.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
      <None Update="res\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
	</ItemGroup>

</Project>
